// ─── Moonshot AI (Kimi) 模型列表 ──────────────────────────────

import type { ModelDef } from "../model-catalog.js";

export const moonshotModels: ModelDef[] = [
  // ── 旗舰多模态 ──────────────────────────────────
  {
    id: "kimi-k2.6",
    name: "Kimi K2.6 (最新旗舰)",
    contextWindow: 256000,
    maxOutputTokens: 98304,
    supportsFunctions: true,
    supportsVision: true,
    supportsReasoning: true,
    supportsStreaming: true,
    fixedTemperature: 1,
    tags: ["flagship", "vision", "agent", "coding"],
    pricing: { input: 1.1, output: 6.5, unit: "CNY/1M_tokens" },
  },
  {
    id: "kimi-k2.5",
    name: "Kimi K2.5",
    contextWindow: 256000,
    maxOutputTokens: 65536,
    supportsFunctions: true,
    supportsVision: true,
    supportsReasoning: true,
    supportsStreaming: true,
    fixedTemperature: 1,
    tags: ["vision", "agent"],
    pricing: { input: 4.0, output: 18.0, unit: "CNY/1M_tokens" },
  },
  // ── 思考模型（深度推理）─────────────────────────
  {
    id: "kimi-k2-thinking",
    name: "Kimi K2 Thinking (长思考)",
    contextWindow: 256000,
    maxOutputTokens: 98304,
    supportsFunctions: true,
    supportsVision: false,
    supportsReasoning: true,
    supportsStreaming: true,
    fixedTemperature: 1,
    tags: ["reasoning", "thinking"],
    pricing: { input: 4.0, output: 24.0, unit: "CNY/1M_tokens" },
  },
  {
    id: "kimi-k2-thinking-turbo",
    name: "Kimi K2 Thinking Turbo (高速思考)",
    contextWindow: 256000,
    maxOutputTokens: 98304,
    supportsFunctions: true,
    supportsVision: false,
    supportsReasoning: true,
    supportsStreaming: true,
    fixedTemperature: 1,
    tags: ["reasoning", "thinking", "fast"],
    pricing: { input: 6.0, output: 36.0, unit: "CNY/1M_tokens" },
  },
  // ── Moonshot V1 文本模型 ────────────────────────
  {
    id: "moonshot-v1-128k",
    name: "Moonshot V1 128K",
    contextWindow: 128000,
    maxOutputTokens: 65536,
    supportsFunctions: true,
    supportsVision: false,
    supportsReasoning: false,
    supportsStreaming: true,
    tags: ["general"],
    pricing: { input: 60, output: 60, unit: "CNY/1M_tokens" },
  },
  {
    id: "moonshot-v1-32k",
    name: "Moonshot V1 32K",
    contextWindow: 32000,
    maxOutputTokens: 32000,
    supportsFunctions: true,
    supportsVision: false,
    supportsReasoning: false,
    supportsStreaming: true,
    tags: ["general", "lightweight"],
    pricing: { input: 24, output: 24, unit: "CNY/1M_tokens" },
  },
  // ── Moonshot V1 视觉模型 ────────────────────────
  {
    id: "moonshot-v1-128k-vision-preview",
    name: "Moonshot V1 128K Vision (视觉)",
    contextWindow: 128000,
    maxOutputTokens: 65536,
    supportsFunctions: true,
    supportsVision: true,
    supportsReasoning: false,
    supportsStreaming: true,
    tags: ["vision", "general"],
    pricing: { input: 60, output: 60, unit: "CNY/1M_tokens" },
  },
  {
    id: "moonshot-v1-32k-vision-preview",
    name: "Moonshot V1 32K Vision (视觉)",
    contextWindow: 32000,
    maxOutputTokens: 32000,
    supportsFunctions: true,
    supportsVision: true,
    supportsReasoning: false,
    supportsStreaming: true,
    tags: ["vision", "lightweight"],
    pricing: { input: 24, output: 24, unit: "CNY/1M_tokens" },
  },
];
