// ─── 通义千问 (Qwen) 模型列表 ─────────────────────────────────

import type { ModelDef } from "../model-catalog.js";

export const qwenModels: ModelDef[] = [
  // ── Qwen3.6 旗舰系列 ────────────────────────────
  {
    id: "qwen3.6-max-preview",
    name: "Qwen3.6 Max Preview (最新旗舰)",
    contextWindow: 262144,
    maxOutputTokens: 65536,
    supportsFunctions: true,
    supportsVision: false,
    supportsReasoning: true,
    supportsStreaming: true,
    tags: ["flagship", "latest"],
    pricing: { input: 2.0, output: 6.0, unit: "CNY/1M_tokens" },
  },
  {
    id: "qwen3.6-plus",
    name: "Qwen3.6 Plus (多模态旗舰)",
    contextWindow: 1000000,
    maxOutputTokens: 65536,
    supportsFunctions: true,
    supportsVision: true,
    supportsReasoning: true,
    supportsStreaming: true,
    tags: ["flagship", "vision", "agent"],
    pricing: { input: 0.8, output: 2.0, unit: "CNY/1M_tokens" },
  },
  {
    id: "qwen3.6-flash",
    name: "Qwen3.6 Flash (极速旗舰)",
    contextWindow: 1000000,
    maxOutputTokens: 65536,
    supportsFunctions: true,
    supportsVision: false,
    supportsReasoning: true,
    supportsStreaming: true,
    tags: ["fast", "latest"],
    pricing: { input: 0.15, output: 0.6, unit: "CNY/1M_tokens" },
  },
  // ── Qwen3.5 系列 ────────────────────────────────
  {
    id: "qwen3.5-plus",
    name: "Qwen3.5 Plus (多模态)",
    contextWindow: 1000000,
    maxOutputTokens: 65536,
    supportsFunctions: true,
    supportsVision: true,
    supportsReasoning: true,
    supportsStreaming: true,
    tags: ["balanced", "vision"],
    pricing: { input: 0.8, output: 2.0, unit: "CNY/1M_tokens" },
  },
  {
    id: "qwen3.5-flash",
    name: "Qwen3.5 Flash",
    contextWindow: 1000000,
    maxOutputTokens: 65536,
    supportsFunctions: true,
    supportsVision: false,
    supportsReasoning: false,
    supportsStreaming: true,
    tags: ["fast"],
    pricing: { input: 0.15, output: 0.6, unit: "CNY/1M_tokens" },
  },
  {
    id: "qwen3.5-omni-plus",
    name: "Qwen3.5 Omni Plus (全模态)",
    contextWindow: 1000000,
    maxOutputTokens: 65536,
    supportsFunctions: true,
    supportsVision: true,
    supportsReasoning: true,
    supportsStreaming: true,
    tags: ["flagship", "vision", "audio", "video"],
    pricing: { input: 2.0, output: 8.0, unit: "CNY/1M_tokens" },
  },
  // ── Qwen3 系列 ──────────────────────────────────
  {
    id: "qwen3-max",
    name: "Qwen3 Max",
    contextWindow: 262144,
    maxOutputTokens: 65536,
    supportsFunctions: true,
    supportsVision: false,
    supportsReasoning: true,
    supportsStreaming: true,
    tags: ["flagship"],
    pricing: { input: 2.0, output: 6.0, unit: "CNY/1M_tokens" },
  },
  // ── Qwen Coder 系列 ─────────────────────────────
  {
    id: "qwen3-coder-plus",
    name: "Qwen3 Coder Plus",
    contextWindow: 1000000,
    maxOutputTokens: 65536,
    supportsFunctions: true,
    supportsVision: false,
    supportsReasoning: true,
    supportsStreaming: true,
    tags: ["coding"],
    pricing: { input: 2.0, output: 6.0, unit: "CNY/1M_tokens" },
  },
  {
    id: "qwen3-coder-flash",
    name: "Qwen3 Coder Flash",
    contextWindow: 1000000,
    maxOutputTokens: 65536,
    supportsFunctions: true,
    supportsVision: false,
    supportsReasoning: true,
    supportsStreaming: true,
    tags: ["coding", "fast"],
    pricing: { input: 0.3, output: 0.9, unit: "CNY/1M_tokens" },
  },
  // ── 经典模型 ────────────────────────────────────
  {
    id: "qwen-plus",
    name: "Qwen Plus (经典)",
    contextWindow: 131072,
    maxOutputTokens: 8192,
    supportsFunctions: true,
    supportsVision: false,
    supportsReasoning: false,
    supportsStreaming: true,
    tags: ["general"],
    pricing: { input: 0.8, output: 2.0, unit: "CNY/1M_tokens" },
  },
  {
    id: "qwen-turbo",
    name: "Qwen Turbo (轻量)",
    contextWindow: 131072,
    maxOutputTokens: 8192,
    supportsFunctions: true,
    supportsVision: false,
    supportsReasoning: false,
    supportsStreaming: true,
    tags: ["lightweight"],
    pricing: { input: 0.3, output: 0.6, unit: "CNY/1M_tokens" },
  },
  // ── 推理 / 长上下文 ─────────────────────────────
  {
    id: "qwq-plus",
    name: "QwQ Plus (深度推理)",
    contextWindow: 131072,
    maxOutputTokens: 65536,
    supportsFunctions: false,
    supportsVision: false,
    supportsReasoning: true,
    supportsStreaming: true,
    tags: ["reasoning"],
    pricing: { input: 2.0, output: 8.0, unit: "CNY/1M_tokens" },
  },
  {
    id: "qwen-long",
    name: "Qwen Long (超长上下文)",
    contextWindow: 10000000,
    maxOutputTokens: 4096,
    supportsFunctions: false,
    supportsVision: false,
    supportsReasoning: false,
    supportsStreaming: true,
    tags: ["long-context"],
    pricing: { input: 0.5, output: 2.0, unit: "CNY/1M_tokens" },
  },
];
