// ─── 智谱 AI (GLM) 模型列表 ───────────────────────────────────

import type { ModelDef } from "../model-catalog.js";

export const zhipuModels: ModelDef[] = [
  // ── 文本模型 ────────────────────────────────────
  {
    id: "GLM-5.1",
    name: "GLM-5.1 (最新旗舰)",
    contextWindow: 200000,
    maxOutputTokens: 128000,
    supportsFunctions: true,
    supportsVision: false,
    supportsReasoning: true,
    supportsStreaming: true,
    tags: ["flagship", "coding"],
    pricing: { input: 6, output: 24, unit: "CNY/1M_tokens" },
  },
  {
    id: "GLM-5",
    name: "GLM-5 高智能",
    contextWindow: 200000,
    maxOutputTokens: 128000,
    supportsFunctions: true,
    supportsVision: false,
    supportsReasoning: true,
    supportsStreaming: true,
    tags: ["agent", "planning"],
    pricing: { input: 5, output: 20, unit: "CNY/1M_tokens" },
  },
  {
    id: "GLM-5-Turbo",
    name: "GLM-5 Turbo (Agent 增强)",
    contextWindow: 200000,
    maxOutputTokens: 128000,
    supportsFunctions: true,
    supportsVision: false,
    supportsReasoning: true,
    supportsStreaming: true,
    tags: ["agent", "coding", "fast"],
    pricing: { input: 5, output: 22, unit: "CNY/1M_tokens" },
  },
  {
    id: "GLM-4.7",
    name: "GLM-4.7 高智能",
    contextWindow: 200000,
    maxOutputTokens: 128000,
    supportsFunctions: true,
    supportsVision: false,
    supportsReasoning: true,
    supportsStreaming: true,
    tags: ["general"],
    pricing: { input: 2, output: 6, unit: "CNY/1M_tokens" },
  },
  {
    id: "GLM-4.5-Air",
    name: "GLM-4.5 Air (高性价比)",
    contextWindow: 128000,
    maxOutputTokens: 96000,
    supportsFunctions: true,
    supportsVision: false,
    supportsReasoning: true,
    supportsStreaming: true,
    tags: ["balanced", "coding"],
    pricing: { input: 0.5, output: 1.5, unit: "CNY/1M_tokens" },
  },
  {
    id: "GLM-4.5-AirX",
    name: "GLM-4.5 AirX (高速性价比)",
    contextWindow: 128000,
    maxOutputTokens: 96000,
    supportsFunctions: true,
    supportsVision: false,
    supportsReasoning: true,
    supportsStreaming: true,
    tags: ["fast", "balanced"],
    pricing: { input: 0.5, output: 1.5, unit: "CNY/1M_tokens" },
  },
  {
    id: "GLM-4.6",
    name: "GLM-4.6 超强性能",
    contextWindow: 200000,
    maxOutputTokens: 128000,
    supportsFunctions: true,
    supportsVision: false,
    supportsReasoning: true,
    supportsStreaming: true,
    tags: ["coding", "reasoning"],
    pricing: { input: 2, output: 6, unit: "CNY/1M_tokens" },
  },
  {
    id: "GLM-4-Long",
    name: "GLM-4 Long (超长上下文)",
    contextWindow: 1000000,
    maxOutputTokens: 4096,
    supportsFunctions: false,
    supportsVision: false,
    supportsReasoning: false,
    supportsStreaming: true,
    tags: ["long-context"],
    pricing: { input: 1, output: 1, unit: "CNY/1M_tokens" },
  },
  // ── 免费 / 轻量文本模型 ─────────────────────────
  {
    id: "GLM-4.7-Flash",
    name: "GLM-4.7 Flash (免费)",
    contextWindow: 200000,
    maxOutputTokens: 128000,
    supportsFunctions: true,
    supportsVision: false,
    supportsReasoning: false,
    supportsStreaming: true,
    tags: ["free", "fast"],
    pricing: { input: 0, output: 0, unit: "CNY/1M_tokens" },
  },
  {
    id: "GLM-4-FlashX-250414",
    name: "GLM-4 FlashX (高速低价)",
    contextWindow: 128000,
    maxOutputTokens: 16000,
    supportsFunctions: true,
    supportsVision: false,
    supportsReasoning: false,
    supportsStreaming: true,
    tags: ["fast", "lightweight"],
    pricing: { input: 0.05, output: 0.2, unit: "CNY/1M_tokens" },
  },
  {
    id: "GLM-4-Flash-250414",
    name: "GLM-4 Flash (免费)",
    contextWindow: 128000,
    maxOutputTokens: 16000,
    supportsFunctions: true,
    supportsVision: false,
    supportsReasoning: false,
    supportsStreaming: true,
    tags: ["free"],
    pricing: { input: 0, output: 0, unit: "CNY/1M_tokens" },
  },
  // ── 视觉模型（支持图片输入）───────────────────────
  {
    id: "GLM-5V-Turbo",
    name: "GLM-5V Turbo (多模态旗舰)",
    contextWindow: 200000,
    maxOutputTokens: 128000,
    supportsFunctions: true,
    supportsVision: true,
    supportsReasoning: true,
    supportsStreaming: true,
    tags: ["flagship", "vision", "coding"],
    pricing: { input: 5, output: 22, unit: "CNY/1M_tokens" },
  },
  {
    id: "GLM-4.6V",
    name: "GLM-4.6V (视觉推理)",
    contextWindow: 128000,
    maxOutputTokens: 32000,
    supportsFunctions: true,
    supportsVision: true,
    supportsReasoning: true,
    supportsStreaming: true,
    tags: ["vision", "reasoning"],
    pricing: { input: 2, output: 6, unit: "CNY/1M_tokens" },
  },
  {
    id: "GLM-4.6V-Flash",
    name: "GLM-4.6V Flash (免费视觉)",
    contextWindow: 128000,
    maxOutputTokens: 32000,
    supportsFunctions: true,
    supportsVision: true,
    supportsReasoning: true,
    supportsStreaming: true,
    tags: ["free", "vision"],
    pricing: { input: 0, output: 0, unit: "CNY/1M_tokens" },
  },
  {
    id: "GLM-4.1V-Thinking-FlashX",
    name: "GLM-4.1V Thinking FlashX (轻量视觉推理)",
    contextWindow: 64000,
    maxOutputTokens: 16000,
    supportsFunctions: false,
    supportsVision: true,
    supportsReasoning: true,
    supportsStreaming: true,
    tags: ["vision", "reasoning", "fast"],
    pricing: { input: 1, output: 4, unit: "CNY/1M_tokens" },
  },
  {
    id: "GLM-4V-Flash",
    name: "GLM-4V Flash (免费视觉)",
    contextWindow: 16000,
    maxOutputTokens: 1000,
    supportsFunctions: false,
    supportsVision: true,
    supportsReasoning: false,
    supportsStreaming: true,
    tags: ["free", "vision", "lightweight"],
    pricing: { input: 0, output: 0, unit: "CNY/1M_tokens" },
  },
];
