/**
 * 进化算子抽象基类（Task 2.2）
 *
 * 借鉴 SE-Agent 的三算子体系：
 * - Revision：生成架构正交的替代策略
 * - Recombination：合成混合策略
 * - Refinement：风险感知的精简优化
 *
 * 支持插件式注册：registerOperator(name, class)
 */

import type { InteractionCase, SkillProposal } from "../engine.js";
import type { AgentManager } from "../../agent/manager.js";
import { safeJsonParseAny } from "../../utils/json-guard.js";

// ═══════════════════════════════════════════════════════════════
// Types
// ═══════════════════════════════════════════════════════════════

/** 算子执行上下文 */
export interface OperatorContext {
  /** 失败案例列表 */
  failureCases: InteractionCase[];
  /** 所有案例 */
  allCases: InteractionCase[];
  /** AgentManager 实例（用于创建分析 Agent） */
  agentManager: AgentManager;
  /** 当前 Agent ID */
  agentId?: string;
}

/** 算子结果 */
export interface OperatorResult {
  /** 生成的技能提案 */
  proposals: SkillProposal[];
  /** 算子名称 */
  operatorName: string;
  /** 执行耗时（ms） */
  durationMs: number;
}

// ═══════════════════════════════════════════════════════════════
// EvolutionOperator 抽象基类
// ═══════════════════════════════════════════════════════════════

export abstract class EvolutionOperator {
  /** 算子唯一名称 */
  abstract readonly name: string;

  /** 人类可读描述 */
  abstract readonly description: string;

  /**
   * 检测当前上下文是否适合使用此算子
   * @returns true 如果此算子适合当前失败场景
   */
  abstract canHandle(context: OperatorContext): boolean;

  /**
   * 执行算子，生成技能提案
   * @param context 算子执行上下文
   * @returns 算子结果（含提案列表）
   */
  abstract process(context: OperatorContext): Promise<OperatorResult>;

  /**
   * 生成 LLM prompt 内容（子类覆写）
   * @param context 算子执行上下文
   * @returns 完整的 prompt 字符串
   */
  protected abstract generateContent(context: OperatorContext): string;

  /**
   * 调用 LLM 并解析响应为 SkillProposal
   */
  protected async callLLM(
    agentManager: AgentManager,
    agentId: string,
    prompt: string,
    failureCases: InteractionCase[],
  ): Promise<SkillProposal[]> {
    const agent = agentManager.getAgent(agentId);
    if (!agent) return [];

    const { response } = await agent.chat(prompt, `operator_${this.name}_${Date.now()}`);
    return this.parseResponse(response, failureCases);
  }

  /**
   * 从 LLM JSON 响应中解析 SkillProposal 列表
   *
   * 支持两种提案模式：
   * 1. 技能进化（.md）：content 为 Markdown 技能内容
   * 2. 源码级进化（.ts）：targetCode 为实际源码修改，
   *    包含 modulePath / targetName / newCode / operation
   */
  protected parseResponse(response: string, cases: InteractionCase[]): SkillProposal[] {
    const proposals: SkillProposal[] = [];
    try {
      const jsonMatch = response.match(/\{[\s\S]*\}/);
      if (!jsonMatch) return proposals;

      const parsed = safeJsonParseAny(jsonMatch[0], `operator-${this.name}`);
      if (!parsed || typeof parsed !== "object") return proposals;
      const rawProposals = (parsed as any).proposals ?? ((parsed as any).action ? [parsed] : []);

      for (const raw of rawProposals) {
        if (!raw.action || raw.action === "no_change") continue;
        const proposal: SkillProposal = {
          id: `prop_${this.name}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2, 6)}`,
          action: raw.action,
          skillName: raw.skillName ?? "unnamed",
          description: raw.description ?? "",
          content: raw.content ?? "",
          reasoning: raw.reasoning ?? `Generated by ${this.name} operator`,
          basedOnCases: cases.slice(0, 5).map((c) => c.id),
          status: "pending",
          createdAt: new Date(),
          patchOperations: raw.patchOperations ?? undefined,
          skillType: raw.skillType ?? undefined,
        };

        // 源码级提案：提取 targetCode 字段
        // LLM 可选产出 targetCode，触发 SelfModificationEngine 直接修改 .ts 源码
        if (raw.targetCode && typeof raw.targetCode === "object") {
          const tc = raw.targetCode;
          if (tc.modulePath && tc.targetName && tc.newCode && tc.operation) {
            proposal.targetCode = {
              modulePath: tc.modulePath,
              targetName: tc.targetName,
              newCode: tc.newCode,
              operation: tc.operation as "modify" | "add" | "delete",
            };
          }
        }

        proposals.push(proposal);
      }
    } catch {
      // JSON 解析失败，返回空
    }
    return proposals;
  }
}

// ═══════════════════════════════════════════════════════════════
// Operator Registry（插件式注册）
// ═══════════════════════════════════════════════════════════════

const operatorRegistry = new Map<string, new () => EvolutionOperator>();

/** 注册一个算子 */
export function registerOperator(name: string, ctor: new () => EvolutionOperator): void {
  operatorRegistry.set(name, ctor);
}

/** 获取所有已注册的算子实例 */
export function getRegisteredOperators(): EvolutionOperator[] {
  return Array.from(operatorRegistry.values()).map((Ctor) => new Ctor());
}

/** 根据名称获取算子实例 */
export function getOperatorByName(name: string): EvolutionOperator | null {
  const Ctor = operatorRegistry.get(name);
  return Ctor ? new Ctor() : null;
}
